Repository Kord-Extensions/kord-extensions, pull requests merged in 2021-10, with the labels that each got.

#98 Add self member tools
  kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/utils/_Guilds.kt
Labels: Type: Enhancement, hacktoberfest-accepted

#99 Extensions to see if a member/role "canInteract" with another Member/Role
  kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/utils/_Member.kt
  kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/utils/_Role.kt
Labels: Type: Enhancement

#97 First approach for a generic registry storage interface
  kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/builders/ExtensibleBotBuilder.kt
  kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/commands/application/ApplicationCommandRegistry.kt
  kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/commands/application/DefaultApplicationCommandRegistry.kt
  kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/commands/application/StorageAwareApplicationCommandRegistry.kt
  kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/components/ComponentContainer.kt
  kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/components/ComponentRegistry.kt
  kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/components/_Functions.kt
  kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/pagination/BaseButtonPaginator.kt
  kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/registry/AbstractDeconstructingApplicationCommandRegistryStorage.kt
  kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/registry/DefaultLocalRegistryStorage.kt
  kord-extensions/src/main/kotlin/com/kotlindiscord/kord/extensions/registry/RegistryStorage.kt
Labels: Status: Awaiting Review, Priority: High, Type: Feature, Type: Enhancement, hacktoberfest-accepted
